#
# Oracle Java 8 Dockerfile
#
# https://github.com/dockerfile/java
# https://github.com/dockerfile/java/tree/master/oracle-java8
#

# Pull base image.
FROM ubuntu:16.04

# Update repo
RUN apt-get update
RUN apt-get install -y software-properties-common python-software-properties
RUN apt-get update

# Define default command.
CMD ["bash"]